// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataLabeling.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddSpecializeInToUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
IF COL_LENGTH('User', 'SpecializeIn') IS NULL
BEGIN
    ALTER TABLE [User] ADD [SpecializeIn] nvarchar(500) NULL;
END
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
IF COL_LENGTH('User', 'SpecializeIn') IS NOT NULL
BEGIN
    ALTER TABLE [User] DROP COLUMN [SpecializeIn];
END
");
        }
    }
}
